name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip  # Use python3 explicitly
          python3 -m pip install -r requirements.txt  # Ensure correct path

      # Step 4: Run tests
      - name: Run pytest
        run: |
          pytest

